### ISSUE TITLE
Битые ссылки

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/bpmcli#55]
При открытии проекта, либо конвертации проект открывается с битыми ссылками
![image](https://user-images.githubusercontent.com/6832799/56769186-1b87b500-67b9-11e9-9ed0-206b557c13b0.png)
Поэтому, ошибки:
![image](https://user-images.githubusercontent.com/6832799/56769207-2c382b00-67b9-11e9-8dd3-0f56c752b040.png)

Решение проблемы:
1) Удалить BpmOnlineSDK
2) Установить опять BpmOnlineSDK

**Comment by alexbondj** [comment]
Исправление планируем внести в рамках задачи #42 Оптимизация работы операции convert
Сделаем более простой способ конвертации а именно:
Не генерировать ref на другие пакеты весь перечень проблем 
Предлагаю закрыть эту таску
