### ISSUE TITLE
Реализовать возможность использования базовых классов

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/bpmcli#56]
В системе невозможно использовать базовые классы
![image](https://user-images.githubusercontent.com/6832799/56769918-47a43580-67bb-11e9-9082-36c9964ce401.png)

**Comment by IlyaChubko** [comment]
Да, схемы из Files/cs не видят классы из исходного кода конфигурации

**Comment by alexbondj** [comment]
Не видят так и есть. И мы пока не планировали это изменять. Все взаимодейсвие происходить через атрибуты и external assembly. Также вариант с reflection будет работать в приложении, но вот для тестов нужно будет что то придумывать. 
Данный подход обеспечивает низкую связаность решений

**Comment by IlyaChubko** [comment]
А у вас есть пример кода reflection для использования классов Files/cs из конфигурации и наоборот?

**Comment by alexbondj** [comment]
Пример использования класса из сборки конфигурации в классе Files/cs
`ObjectHandle handle = Activator.CreateInstance("Terrasoft.Configuration", "Terrasoft.Configuration.ReportService.ReportHelper");
object p = handle.Unwrap();
Type t = p.GetType();
PropertyInfo prop = t.GetProperty("UserConnection");
if (prop != null)
	return (prop.GetValue(p) as UserConnection).CurrentUser.ContactName;`

**Comment by alexbondj** [comment]
@IlyaChubko таску можем закрыть или есть еще вопросы?
