### ISSUE TITLE
Проблемы при конвертации пакета

### ISSUE THREAD

**Issue by IlyaChubko** [Advance-Technologies-Foundation/bpmcli#57]
При перемещении cs схем в Files/cs имеются проблемы в случае, когда в событии объекта есть обращение к классам, которые были перемещены.
Самое главное, что система не компилируется и не позволяет зайти в событийный подпроцесс из-за того, что нескомпилирована. Вот такой замкнутый круг.
Пруфы:
![image](https://user-images.githubusercontent.com/6832799/56786527-f66b6480-6801-11e9-93c2-9cff35ce7c1f.png)
![image](https://user-images.githubusercontent.com/6832799/56786539-008d6300-6802-11e9-87ef-7194e08a187c.png)

**Comment by alexbondj** [comment]
Исправление планируем внести в рамках задачи #42 Оптимизация работы операции convert
Сделаем более простой способ конвертации а именно:
При конвертации пакета не переводить существующий код
Предлагаю закрыть эту таску
