### ISSUE TITLE
generate-pkg-zip Не работает для создания единого архива пакетов

### ISSUE THREAD

**Issue by adamenko-ipt** [Advance-Technologies-Foundation/bpmcli#79]
В файле [generate-pkg-zip.txt](https://github.com/Advance-Technologies-Foundation/bpmcli/blob/master/bpmcli/help/en/generate-pkg-zip.txt) Есть такое описание 
_bpmcli generate-pkg-zip <PACKAGE_NAME_1>,<PACKAGE_NAME_2>,<PACKAGE_NAME_3>
        compress more than one packages to single .gz file if command run from 
        packages containing directory_

При попытке добавить более одного пакет, 
`..\Terrasoft.WebApp\Terrasoft.Configuration\Pkg> bpmcli generate-pkg-zip "Base" "Top" -d "D:\pkg\packages.gz"`
если их указывать через запятую, то он возвращает ошибку пути, обращаясь по пути включая запятую
**Could not find a part of the path** `..\Terrasoft.WebApp\Terrasoft.Configuration\Pkg\GPN.Common.Base,\descriptor.json `

Если указывать название через пробел, то он берёт первый пакет и на этом всё =(

**Comment by IlyaChubko** [comment]
Добрый день!
Данная команда работает следующим образом:
bpmcli generate-pkg-zip <путь до Pkg> -p <список пакетов через запятую без пробелов> -d <путь до файла с указанием файла zip куда будет выгружен пакет>
Например,
bpmcli generate-pkg-zip C:\inetpub\wwwroot\Site\Terrasoft.WebApp\Terrasoft.Configuration\Pkg\ -p Package1,Package2,Package3 -d C:\Packages.zip

**Comment by adamenko-ipt** [comment]
Спасибо, помогло.
